export const moroccanCities = [
  {
    "region": "Rabat-Sale-Kenitra",
    "cities": [
      "Rabat",
      "Sale",
      "Sale El Jadida",
      "Temara",
      "Harhoura",
      "Sidi Taibi",
      "Mers Lkhir",
      "Oudaya",
      "Skhirat",
      "Kenitra",
      "Tamesna",
      "Ain Aouda",
      "Ain Attig",
      "Sidi Allal El Bahraoui",
      "Sidi Bouknadel",
      "Mehdia",
      "Khemisset",
      "Sidi Kacem",
      "Sidi Slimane",
      "Mechra Bel Ksiri",
      "Moulay Bousselham",
      "Sidi Allal Tazi",
      "Sidi Yahya El Gharb",
      "Khenichet",
      "Sidi Yahya Zaer",
      "Tiflet",
      "Romani",
      "Maaziz",
      "Oulmes",
      "Lalla Mimouna",
      "Had Kourt"
    ]
  },
  {
    "region": "Casablanca-Settat",
    "cities": [
      "Casablanca",
      "Mohammedia",
      "Tamaris",
      "Sidi Rahal",
      "Nouaceur",
      "Mediouna",
      "Ain Harrouda",
      "Zenata",
      "Bouskoura",
      "Tit Mellil",
      "Had Soualem",
      "Errahma",
      "Dar Bouazza",
      "Deroua",
      "Lahraouyine",
      "Sidi Massoud",
      "La Ville Verte",
      "El Garra",
      "Ben Yakhlef",
      "El Mansouria",
      "Benslimane",
      "Ben Ahmed",
      "Bouznika",
      "Settat",
      "Berrechid",
      "Brouj"
    ]
  },
  {
    "region": "Fes-Meknes",
    "cities": [
      "Fes",
      "Meknes",
      "Sefrou",
      "Boulmane",
      "Boulemane",
      "El Hajeb",
      "Ifrane",
      "Ain Chkef",
      "Ain Allah",
      "Sidi Harazem",
      "Ain Beida",
      "Bhalil",
      "Ras El Ma Fes",
      "Ouled Tayeb",
      "El Menzel",
      "Imouzzer Kandar",
      "Ain Cheggag",
      "Boufakrane",
      "El Haj Kaddour",
      "Agourai",
      "Moulay Idriss Zerhoun",
      "Sabaa Aiyoun",
      "Ain Taoujdate",
      "Kariat Ba Mohamed",
      "Missour",
      "Outat El Haj",
      "Ghafsai",
      "Douiet",
      "Ribate El Kheir",
      "Taza",
      "Taounate",
      "Tahla",
      "Ain Aicha",
      "Tizi Oussli"
    ]
  },
  {
    "region": "Marrakech-Safi",
    "cities": [
      "Marrakech",
      "Safi",
      "Essaouira",
      "Chichaoua",
      "Kelaa Des Sraghna",
      "Youssoufia",
      "Ourika",
      "Ait Ourir",
      "Tahannaout",
      "El Attaouia",
      "Echemmaia",
      "Imintanoute",
      "Demnate",
      "Tamelelt",
      "Skhour Rhamna",
      "Ben Guerir",
      "Sidi Bou Othmane",
      "Sidi Bouzid Safi",
      "Oualidia",
      "Sebt Gzoula",
      "Jamaat Shaim",
      "Hrara Safi",
      "Smimou"
    ]
  },
  {
    "region": "Souss-Massa",
    "cities": [
      "Agadir",
      "Inezgane",
      "Ait Melloul",
      "Chtouka Ait Baha",
      "Taroudant",
      "Tiznit",
      "Dcheira",
      "Tikiouine",
      "Tarrast",
      "Aglou",
      "Tafraoute",
      "Bounaamane Tiznit",
      "Ouled Jerrar",
      "Massa",
      "Ait Amira",
      "Belfaa",
      "Tin Mansour",
      "Biougra",
      "Inchaden",
      "Leqliaa",
      "Ait Baha",
      "Oulad Berhil",
      "Houara",
      "Taliouine",
      "Oulad Teima",
      "Oulad Dahou",
      "Lagfifat",
      "Aoulouz",
      "Temsia",
      "Sebt El Guerdane",
      "Anza",
      "Aourir",
      "Imi Ouaddar",
      "Taghazout",
      "Tamraght"
    ]
  },
  {
    "region": "Tanger-Tetouan-Al Hoceima",
    "cities": [
      "Tanger",
      "Beni Mekada",
      "Tetouan",
      "Martil",
      "Mdiq",
      "Fnideq",
      "Assilah",
      "Asilah",
      "Larache",
      "Ksar El Kebir",
      "Chefchaouen",
      "Al Hoceima",
      "Ouazzane",
      "Gueznaia",
      "Kasbah Taher",
      "Ksar Sghir",
      "Cabo Negro",
      "Marina Smir",
      "Kabila",
      "Souk Khemis Du Sahel",
      "Bouzaghlal",
      "Azla",
      "Bouanane Tetouan",
      "Laouamra",
      "Ain Dorij",
      "Zoumi Ouazzane",
      "Ounnana",
      "Jorf El Melha",
      "Ajdir Al Hoceima",
      "Targuist",
      "Imzouren",
      "Bab Taza",
      "Issaguen",
      "Oued Laou",
      "Beni Bouayach Al Hoceima",
      "Bab Berred",
      "Stihat"
    ]
  },
  {
    "region": "Oriental",
    "cities": [
      "Oujda",
      "Berkane",
      "Nador",
      "Taourirt",
      "Jerada",
      "Figuig",
      "Driouch",
      "Guercif",
      "Zeghanghane",
      "Bouarg",
      "Jaadar",
      "Beni Ensar",
      "Selouane",
      "Al Aaroui",
      "Mariouari",
      "Barichino",
      "Tiztoutine",
      "Beni Chiker",
      "Farkhana",
      "Beni Sidal Jbel",
      "Kariat Arekmane Nador",
      "Zaio",
      "Ouled Settout",
      "Ben Aib",
      "Tafersit",
      "Midar",
      "Kassita",
      "Telat Azlaf",
      "Dar El Kebdani",
      "Ahfir",
      "Ain Erreggada",
      "Aklim",
      "Boughriba",
      "Madagh",
      "Saaidia",
      "Beni Drar",
      "Ain Beni Mathar",
      "Tendrara",
      "Bouarfa",
      "Laayoune Charkia",
      "Aayoune Charkia",
      "Ras El Ma"
    ]
  },
  {
    "region": "Beni Mellal-Khenifra",
    "cities": [
      "Beni Mellal",
      "Khenifra",
      "Khouribga",
      "Azilal",
      "Fqih Ben Salah",
      "Fquih Ben Salah",
      "Afourar",
      "Zaouiat Cheikh",
      "Tagzirt Beni Mellal",
      "Souk El Had Des Bradia",
      "Sidi Jaber Beni Mellal",
      "Oulad Ayad",
      "Timoulilte Beni Mellal",
      "Kasba Tadla",
      "Oued Zem",
      "Ouled Mbarek Beni Mellal",
      "Souk Sebt Oulad Nemma",
      "Bejaad",
      "Ighrem Laalam",
      "Oulad Zemam",
      "Sidi Aissa Ben Ali",
      "Dar Ould Zidouh",
      "Bni Ayat",
      "Mrirt",
      "Laayayta",
      "Oulad Yaich",
      "Oulad Ali Beni Mellal",
      "Oulad Youssef",
      "El Ksiba Beni Mellal",
      "Foum Oudi Beni Mellal",
      "Ouled Said El Oued",
      "Boujniba",
      "Ait Rbaa",
      "Tachrafat",
      "Ouled Driss",
      "Oulad Mrah",
      "Ouled Smail",
      "Al Khalfia",
      "Ait Ali",
      "Tanougha Beni Mellal",
      "Foum El Ansar",
      "Adouz",
      "Ouled Moussa Beni Mellal",
      "El Borj Khenifra",
      "Lahri Khenifra",
      "Tighassaline",
      "Aguelmous",
      "El Kebab Khenifra",
      "Ait Ishaq",
      "Ouaouizeght",
      "Ouaoumana",
      "Had Boumoussa",
      "Kaf Nsour Khenifra",
      "Moulay Bouazza Khenifra",
      "Hattane Khouribga",
      "Boulanouare Khouribga"
    ]
  },
  {
    "region": "Draa-Tafilalet",
    "cities": [
      "Errachidia",
      "Ouarzazate",
      "Zagora",
      "Tinghir",
      "Midelt",
      "Arfoud",
      "Rissani",
      "Rich",
      "Tinejdad",
      "Zaida",
      "Boumia",
      "Golmima",
      "Boudnib",
      "Merzouga",
      "Skoura",
      "Idlsn Ouarzazate",
      "Boumalne Dades",
      "Boumalen Dades",
      "Kelaat Mgouna",
      "Agdz",
      "Imghran",
      "Agwim",
      "Amerzgan",
      "Ighrem Nougdal",
      "Ait Zineb",
      "Tidili",
      "Wad Lmalh",
      "Ait Ben Haddou",
      "Taznakht",
      "Aghbalou Nisrdane Errachidia"
    ]
  },
  {
    "region": "Guelmim-Oued Noun",
    "cities": [
      "Guelmim",
      "Tan-Tan",
      "Tantan",
      "Sidi Ifni",
      "Assa-Zag",
      "Bouizakarne",
      "El Ouatia",
      "Foum Lahcen Tata",
      "Tata",
      "Akka",
      "Foum Zguid",
      "Tagmout Tata",
      "Tissint Tata",
      "Issafen Tata"
    ]
  },
  {
    "region": "Laayoune-Sakia El Hamra",
    "cities": [
      "Laayoune",
      "Boujdour",
      "Tarfaya",
      "Smara",
      "Essmara",
      "Akhfenir"
    ]
  },
  {
    "region": "Dakhla-Oued Ed-Dahab",
    "cities": [
      "Dakhla"
    ]
  }
]
.sort((a, b) => a.region.localeCompare(b.region));